---
- hosts: all
  tasks:
  - name: Find folders to delete
    find:
      paths: /home/cloud_user/{{ item }}
      recurse: true
      file_type: directory
      excludes: 'APP,DEN'
    loop: "{{ dir_name }}"
    register: dirs_to_delete

  - name: Find files to delete
    find:
      paths: /home/cloud_user/{{ item }}
      recurse: true
    loop: "{{ dir_name }}"
    register: files_to_delete

  - debug: "msg=dirs_to_delete"
  - debug: "msg=files_to_delete" 
  

  # - name: Delete files and folders
  #   file:
  #     path: "{{ item.path }}"
  #     state: absent      
  #   with_items: 
  #   - "{{ files_to_delete.files }}"
  #   - "{{ dirs_to_delete.files }}"
  