---
- hosts: all
  tasks:
  - name: Ansible delete dir
    find:
      paths: /home/cloud_user/{{dir_name}}
      recurse: true
      file_type: directory
      excludes: 'APP,DEN'
    register: dirs_to_delete

  - name: Ansible delete files
    find:
      paths: /home/cloud_user/{{dir_name}}
      recurse: true
    register: files_to_delete

  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent      
    with_items: 
    - "{{ files_to_delete.files }}"
    - "{{ dirs_to_delete.files }}"
  