---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Create index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World!!"
